export const prepareConfig = {
    sourceDir: ".",
    outputDir: "build/web-ext-firefox-src",
    firefoxManifestFile: "manifest_firefox.json",
    outputManifestFile: "manifest.json",
    rsyncExcludes: [
        ".git",
        ".github",
        ".serena",
        ".codex",
        ".DS_Store",
        "build",
        ".webext-profile",
        "utils",
        "node_modules",
        "pnpm-lock.yaml",
        "tsconfig*.json",
        "*.ts",
        "*.map",
    ],
};
