name: Release

on:
    workflow_dispatch:
        inputs:
            tag_name:
                description: "Tag name to create (e.g., v1.0.0)"
                required: true

jobs:
    build-and-release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: read

        steps:
            - name: Checkout Code
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # checkout v6.0.2
              with:
                  fetch-depth: 0 # Retrieve full history.

            - name: Create ZIP File
              run: |
                  # Ensure executable permission.
                  chmod +x ./package.sh
                  ./package.sh

            - name: Fetch Latest Merged PR Infomation
              env:
                  GH_TOKEN: ${{ github.token }}
              run: |
                  # Get title and body of the latest merged PR.
                  gh pr list --state merged --base Release --limit 1 --json title,body --template \
                  '{{ range . }}# {{ .title }}{{ "\n\n" }}{{ .body }}{{ end }}' > release_notes.md

            - name: Create Release
              env:
                  GH_TOKEN: ${{ github.token }}
                  TAG_NAME: ${{ github.event.inputs.tag_name }}
              run: |
                  gh release create "$TAG_NAME" \
                    ./package/*.zip \
                    --title "Release $TAG_NAME" \
                    --notes-file release_notes.md \
                    --draft
